if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

alias ll='ls -al'
alias lb='cd ..;ls'
alias text='subl'
alias FUCKYOUECLIPSE='/Applications/eclipse/eclipse -clean'

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
alias ls='ls -GFh'

# startup virtualenv-burrito
if [ -f $HOME/.venvburrito/startup.sh ]; then
    . $HOME/.venvburrito/startup.sh
fi





set editing-mode vi
set keymap vi
set -o vi
